// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addmobile.sql

package db

import (
	"context"
)

const addStudentMobile = `-- name: AddStudentMobile :exec
INSERT INTO
  student_mobiles (student_id, mobile)
VALUES
  ($1, $2)
`

type AddStudentMobileParams struct {
	StudentID int32
	Mobile    string
}

func (q *Queries) AddStudentMobile(ctx context.Context, arg AddStudentMobileParams) error {
	_, err := q.db.Exec(ctx, addStudentMobile, arg.StudentID, arg.Mobile)
	return err
}
