// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdmissionTest struct {
	TestID       int32
	UniversityID int32
	PrereqTestID pgtype.Int4
	ExamUnit     string
	ExamCenter   string
}

type Application struct {
	ApplicationID  int32
	StudentID      int32
	ProgramID      int32
	SubmissionDate pgtype.Timestamp
	Status         pgtype.Text
}

type Notification struct {
	StudentID      int32
	NotificationID int32
	Message        string
	DeadlineDate   pgtype.Timestamp
}

type Payment struct {
	PaymentID     int32
	ApplicationID int32
	TransactionID string
	Amount        pgtype.Numeric
	PaymentMethod string
	PaymentStatus pgtype.Text
	Timestamp     pgtype.Timestamp
}

type Program struct {
	ProgramID        int32
	UniversityID     int32
	ProgramName      string
	ProgramUnit      string
	TotalSeats       int32
	MinSscGpa        pgtype.Numeric
	MinHscGpa        pgtype.Numeric
	RequiredHscGroup string
	MinMath          pgtype.Numeric
	MinPhysics       pgtype.Numeric
	MinChemistry     pgtype.Numeric
	MinEnglish       pgtype.Numeric
	MinBangla        pgtype.Numeric
	PrevCutoffMarks  pgtype.Numeric
}

type Student struct {
	StudentID   int32
	FirstName   string
	LastName    string
	Email       string
	Password    string
	DateOfBirth pgtype.Date
	SscRoll     int32
	SscReg      int32
	SscGpa      pgtype.Numeric
	SscBoard    string
	SscYear     int32
	HscRoll     int32
	HscReg      int32
	HscGpa      pgtype.Numeric
	HscBoard    string
	HscYear     int32
}

type StudentMobile struct {
	StudentID int32
	Mobile    string
}

type StudentTestResult struct {
	StudentID     int32
	TestID        int32
	MarksObtained pgtype.Numeric
	MeritPosition pgtype.Int4
}

type University struct {
	UniversityID    int32
	UniversityName  string
	Website         pgtype.Text
	LocationAddress pgtype.Text
	TransportRoutes pgtype.Text
	EstTravelTime   pgtype.Text
}
