// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddStudentMobile(ctx context.Context, arg AddStudentMobileParams) error
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	CreateUniversity(ctx context.Context, arg CreateUniversityParams) (University, error)
	GetStudent(ctx context.Context, studentID int32) (Student, error)
	GetUniversity(ctx context.Context, universityID int32) (University, error)
	ListUniversities(ctx context.Context) ([]University, error)
}

var _ Querier = (*Queries)(nil)
