// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO
  students (
    first_name,
    last_name,
    email,
    password,
    date_of_birth,
    ssc_roll,
    ssc_reg,
    ssc_gpa,
    ssc_board,
    ssc_year,
    hsc_roll,
    hsc_reg,
    hsc_gpa,
    hsc_board,
    hsc_year
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
  )
RETURNING
  student_id, first_name, last_name, email, password, date_of_birth, ssc_roll, ssc_reg, ssc_gpa, ssc_board, ssc_year, hsc_roll, hsc_reg, hsc_gpa, hsc_board, hsc_year
`

type CreateStudentParams struct {
	FirstName   string
	LastName    string
	Email       string
	Password    string
	DateOfBirth pgtype.Date
	SscRoll     int32
	SscReg      int32
	SscGpa      pgtype.Numeric
	SscBoard    string
	SscYear     int32
	HscRoll     int32
	HscReg      int32
	HscGpa      pgtype.Numeric
	HscBoard    string
	HscYear     int32
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.DateOfBirth,
		arg.SscRoll,
		arg.SscReg,
		arg.SscGpa,
		arg.SscBoard,
		arg.SscYear,
		arg.HscRoll,
		arg.HscReg,
		arg.HscGpa,
		arg.HscBoard,
		arg.HscYear,
	)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.DateOfBirth,
		&i.SscRoll,
		&i.SscReg,
		&i.SscGpa,
		&i.SscBoard,
		&i.SscYear,
		&i.HscRoll,
		&i.HscReg,
		&i.HscGpa,
		&i.HscBoard,
		&i.HscYear,
	)
	return i, err
}

const getStudent = `-- name: GetStudent :one
SELECT
  student_id, first_name, last_name, email, password, date_of_birth, ssc_roll, ssc_reg, ssc_gpa, ssc_board, ssc_year, hsc_roll, hsc_reg, hsc_gpa, hsc_board, hsc_year
FROM
  students
WHERE
  student_id = $1
LIMIT
  1
`

func (q *Queries) GetStudent(ctx context.Context, studentID int32) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, studentID)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.DateOfBirth,
		&i.SscRoll,
		&i.SscReg,
		&i.SscGpa,
		&i.SscBoard,
		&i.SscYear,
		&i.HscRoll,
		&i.HscReg,
		&i.HscGpa,
		&i.HscBoard,
		&i.HscYear,
	)
	return i, err
}
