// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: universities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUniversity = `-- name: CreateUniversity :one
INSERT INTO
  universities (
    university_name,
    website,
    location_address,
    transport_routes,
    est_travel_time
  )
VALUES
  ($1, $2, $3, $4, $5)
RETURNING
  university_id, university_name, website, location_address, transport_routes, est_travel_time
`

type CreateUniversityParams struct {
	UniversityName  string
	Website         pgtype.Text
	LocationAddress pgtype.Text
	TransportRoutes pgtype.Text
	EstTravelTime   pgtype.Text
}

func (q *Queries) CreateUniversity(ctx context.Context, arg CreateUniversityParams) (University, error) {
	row := q.db.QueryRow(ctx, createUniversity,
		arg.UniversityName,
		arg.Website,
		arg.LocationAddress,
		arg.TransportRoutes,
		arg.EstTravelTime,
	)
	var i University
	err := row.Scan(
		&i.UniversityID,
		&i.UniversityName,
		&i.Website,
		&i.LocationAddress,
		&i.TransportRoutes,
		&i.EstTravelTime,
	)
	return i, err
}

const getUniversity = `-- name: GetUniversity :one
SELECT
  university_id, university_name, website, location_address, transport_routes, est_travel_time
FROM
  universities
WHERE
  university_id = $1
LIMIT
  1
`

func (q *Queries) GetUniversity(ctx context.Context, universityID int32) (University, error) {
	row := q.db.QueryRow(ctx, getUniversity, universityID)
	var i University
	err := row.Scan(
		&i.UniversityID,
		&i.UniversityName,
		&i.Website,
		&i.LocationAddress,
		&i.TransportRoutes,
		&i.EstTravelTime,
	)
	return i, err
}

const listUniversities = `-- name: ListUniversities :many
SELECT
  university_id, university_name, website, location_address, transport_routes, est_travel_time
FROM
  universities
ORDER BY
  university_name
`

func (q *Queries) ListUniversities(ctx context.Context) ([]University, error) {
	rows, err := q.db.Query(ctx, listUniversities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []University
	for rows.Next() {
		var i University
		if err := rows.Scan(
			&i.UniversityID,
			&i.UniversityName,
			&i.Website,
			&i.LocationAddress,
			&i.TransportRoutes,
			&i.EstTravelTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
