// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"database/sql"
)

const adminUpdateApplicationStatus = `-- name: AdminUpdateApplicationStatus :exec
UPDATE Application
SET status = ?
WHERE app_id = ?
`

type AdminUpdateApplicationStatusParams struct {
	Status string `json:"status"`
	AppID  int32  `json:"app_id"`
}

func (q *Queries) AdminUpdateApplicationStatus(ctx context.Context, arg AdminUpdateApplicationStatusParams) error {
	_, err := q.db.ExecContext(ctx, adminUpdateApplicationStatus, arg.Status, arg.AppID)
	return err
}

const getUniversityApplications = `-- name: GetUniversityApplications :many
SELECT
    a.app_id,
    a.student_id,
    a.program_id,
    p.p_name AS program_name,
    a.status,
    a.sub_date
FROM Application a
JOIN Program p ON a.program_id = p.program_id
WHERE p.u_id = ?
ORDER BY a.sub_date DESC
`

type GetUniversityApplicationsRow struct {
	AppID       int32        `json:"app_id"`
	StudentID   int32        `json:"student_id"`
	ProgramID   int32        `json:"program_id"`
	ProgramName string       `json:"program_name"`
	Status      string       `json:"status"`
	SubDate     sql.NullTime `json:"sub_date"`
}

func (q *Queries) GetUniversityApplications(ctx context.Context, uID int32) ([]GetUniversityApplicationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUniversityApplications, uID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUniversityApplicationsRow
	for rows.Next() {
		var i GetUniversityApplicationsRow
		if err := rows.Scan(
			&i.AppID,
			&i.StudentID,
			&i.ProgramID,
			&i.ProgramName,
			&i.Status,
			&i.SubDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
