// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"
	"database/sql"
)

const createApplication = `-- name: CreateApplication :execresult
INSERT INTO Application (program_id, student_id, status)
VALUES (?, ?, 'Pending')
`

type CreateApplicationParams struct {
	ProgramID int32 `json:"program_id"`
	StudentID int32 `json:"student_id"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createApplication, arg.ProgramID, arg.StudentID)
}

const getProgramRequiredFields = `-- name: GetProgramRequiredFields :many
SELECT field_name
FROM Program_Required_Fields
WHERE program_id = ?
`

func (q *Queries) GetProgramRequiredFields(ctx context.Context, programID int32) ([]ProgramRequiredFieldsFieldName, error) {
	rows, err := q.db.QueryContext(ctx, getProgramRequiredFields, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgramRequiredFieldsFieldName
	for rows.Next() {
		var field_name ProgramRequiredFieldsFieldName
		if err := rows.Scan(&field_name); err != nil {
			return nil, err
		}
		items = append(items, field_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentApplications = `-- name: GetStudentApplications :many
SELECT
    a.app_id,
    a.program_id,
    a.sub_date,
    a.status,
    p.p_name AS program_name,
    u.u_name AS university_name
FROM Application a
JOIN Program p ON a.program_id = p.program_id
JOIN University u ON p.u_id = u.u_id
WHERE a.student_id = ?
ORDER BY a.sub_date DESC
`

type GetStudentApplicationsRow struct {
	AppID          int32        `json:"app_id"`
	ProgramID      int32        `json:"program_id"`
	SubDate        sql.NullTime `json:"sub_date"`
	Status         string       `json:"status"`
	ProgramName    string       `json:"program_name"`
	UniversityName string       `json:"university_name"`
}

func (q *Queries) GetStudentApplications(ctx context.Context, studentID int32) ([]GetStudentApplicationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStudentApplications, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentApplicationsRow
	for rows.Next() {
		var i GetStudentApplicationsRow
		if err := rows.Scan(
			&i.AppID,
			&i.ProgramID,
			&i.SubDate,
			&i.Status,
			&i.ProgramName,
			&i.UniversityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentProfileFields = `-- name: GetStudentProfileFields :many
SELECT field_name
FROM Student_Profile_Info
WHERE student_id = ?
`

func (q *Queries) GetStudentProfileFields(ctx context.Context, studentID int32) ([]StudentProfileInfoFieldName, error) {
	rows, err := q.db.QueryContext(ctx, getStudentProfileFields, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentProfileInfoFieldName
	for rows.Next() {
		var field_name StudentProfileInfoFieldName
		if err := rows.Scan(&field_name); err != nil {
			return nil, err
		}
		items = append(items, field_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPayment = `-- name: RecordPayment :execresult
INSERT INTO Payment (tx_id, amount, status, method, app_id)
VALUES (?, ?, ?, ?, ?)
`

type RecordPaymentParams struct {
	TxID   string `json:"tx_id"`
	Amount string `json:"amount"`
	Status string `json:"status"`
	Method string `json:"method"`
	AppID  int32  `json:"app_id"`
}

func (q *Queries) RecordPayment(ctx context.Context, arg RecordPaymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, recordPayment,
		arg.TxID,
		arg.Amount,
		arg.Status,
		arg.Method,
		arg.AppID,
	)
}
