// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type ProgramRequiredFieldsFieldName string

const (
	ProgramRequiredFieldsFieldNamePRESENTADDRESS   ProgramRequiredFieldsFieldName = "PRESENT_ADDRESS"
	ProgramRequiredFieldsFieldNamePERMANENTADDRESS ProgramRequiredFieldsFieldName = "PERMANENT_ADDRESS"
	ProgramRequiredFieldsFieldNameFATHERSNAME      ProgramRequiredFieldsFieldName = "FATHERS_NAME"
	ProgramRequiredFieldsFieldNameMOTHERSNAME      ProgramRequiredFieldsFieldName = "MOTHERS_NAME"
	ProgramRequiredFieldsFieldNameBLOODGROUP       ProgramRequiredFieldsFieldName = "BLOOD_GROUP"
	ProgramRequiredFieldsFieldNameQUOTA            ProgramRequiredFieldsFieldName = "QUOTA"
	ProgramRequiredFieldsFieldNamePHOTOURL         ProgramRequiredFieldsFieldName = "PHOTO_URL"
	ProgramRequiredFieldsFieldNameSIGNATUREURL     ProgramRequiredFieldsFieldName = "SIGNATURE_URL"
)

func (e *ProgramRequiredFieldsFieldName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProgramRequiredFieldsFieldName(s)
	case string:
		*e = ProgramRequiredFieldsFieldName(s)
	default:
		return fmt.Errorf("unsupported scan type for ProgramRequiredFieldsFieldName: %T", src)
	}
	return nil
}

type NullProgramRequiredFieldsFieldName struct {
	ProgramRequiredFieldsFieldName ProgramRequiredFieldsFieldName `json:"program_required_fields_field_name"`
	Valid                          bool                           `json:"valid"` // Valid is true if ProgramRequiredFieldsFieldName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProgramRequiredFieldsFieldName) Scan(value interface{}) error {
	if value == nil {
		ns.ProgramRequiredFieldsFieldName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProgramRequiredFieldsFieldName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProgramRequiredFieldsFieldName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProgramRequiredFieldsFieldName), nil
}

type StudentMobileOwnerType string

const (
	StudentMobileOwnerTypeSelf   StudentMobileOwnerType = "self"
	StudentMobileOwnerTypeMother StudentMobileOwnerType = "mother"
	StudentMobileOwnerTypeFather StudentMobileOwnerType = "father"
)

func (e *StudentMobileOwnerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StudentMobileOwnerType(s)
	case string:
		*e = StudentMobileOwnerType(s)
	default:
		return fmt.Errorf("unsupported scan type for StudentMobileOwnerType: %T", src)
	}
	return nil
}

type NullStudentMobileOwnerType struct {
	StudentMobileOwnerType StudentMobileOwnerType `json:"student_mobile_owner_type"`
	Valid                  bool                   `json:"valid"` // Valid is true if StudentMobileOwnerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStudentMobileOwnerType) Scan(value interface{}) error {
	if value == nil {
		ns.StudentMobileOwnerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StudentMobileOwnerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStudentMobileOwnerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StudentMobileOwnerType), nil
}

type StudentProfileInfoFieldName string

const (
	StudentProfileInfoFieldNamePRESENTADDRESS   StudentProfileInfoFieldName = "PRESENT_ADDRESS"
	StudentProfileInfoFieldNamePERMANENTADDRESS StudentProfileInfoFieldName = "PERMANENT_ADDRESS"
	StudentProfileInfoFieldNameFATHERSNAME      StudentProfileInfoFieldName = "FATHERS_NAME"
	StudentProfileInfoFieldNameMOTHERSNAME      StudentProfileInfoFieldName = "MOTHERS_NAME"
	StudentProfileInfoFieldNameBLOODGROUP       StudentProfileInfoFieldName = "BLOOD_GROUP"
	StudentProfileInfoFieldNameQUOTA            StudentProfileInfoFieldName = "QUOTA"
	StudentProfileInfoFieldNamePHOTOURL         StudentProfileInfoFieldName = "PHOTO_URL"
	StudentProfileInfoFieldNameSIGNATUREURL     StudentProfileInfoFieldName = "SIGNATURE_URL"
)

func (e *StudentProfileInfoFieldName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StudentProfileInfoFieldName(s)
	case string:
		*e = StudentProfileInfoFieldName(s)
	default:
		return fmt.Errorf("unsupported scan type for StudentProfileInfoFieldName: %T", src)
	}
	return nil
}

type NullStudentProfileInfoFieldName struct {
	StudentProfileInfoFieldName StudentProfileInfoFieldName `json:"student_profile_info_field_name"`
	Valid                       bool                        `json:"valid"` // Valid is true if StudentProfileInfoFieldName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStudentProfileInfoFieldName) Scan(value interface{}) error {
	if value == nil {
		ns.StudentProfileInfoFieldName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StudentProfileInfoFieldName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStudentProfileInfoFieldName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StudentProfileInfoFieldName), nil
}

type AdmissionTest struct {
	TestID       int32          `json:"test_id"`
	ExamUnit     sql.NullString `json:"exam_unit"`
	ExamCenter   sql.NullString `json:"exam_center"`
	PrereqTestID sql.NullInt32  `json:"prereq_test_id"`
	ExamDate     sql.NullTime   `json:"exam_date"`
	ProgramID    sql.NullInt32  `json:"program_id"`
}

type Application struct {
	AppID     int32        `json:"app_id"`
	SubDate   sql.NullTime `json:"sub_date"`
	Status    string       `json:"status"`
	ProgramID int32        `json:"program_id"`
	StudentID int32        `json:"student_id"`
}

type Conduct struct {
	UID    int32 `json:"u_id"`
	TestID int32 `json:"test_id"`
}

type Gife struct {
	StudentID     int32          `json:"student_id"`
	TestID        int32          `json:"test_id"`
	Marks         sql.NullString `json:"marks"`
	MeritPosition sql.NullInt32  `json:"merit_position"`
}

type Notification struct {
	NotifID   int32        `json:"notif_id"`
	StudentID int32        `json:"student_id"`
	Message   string       `json:"message"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Payment struct {
	PaymentID int32        `json:"payment_id"`
	TxID      string       `json:"tx_id"`
	Amount    string       `json:"amount"`
	Status    string       `json:"status"`
	Method    string       `json:"method"`
	Timestamp sql.NullTime `json:"timestamp"`
	AppID     int32        `json:"app_id"`
}

type Program struct {
	ProgramID      int32          `json:"program_id"`
	PName          string         `json:"p_name"`
	PUnit          sql.NullString `json:"p_unit"`
	TotalSeats     int32          `json:"total_seats"`
	PrevCutmarks   sql.NullString `json:"prev_cutmarks"`
	Deadline       time.Time      `json:"deadline"`
	UID            int32          `json:"u_id"`
	ApplicationFee string         `json:"application_fee"`
}

type ProgramEligibilityRule struct {
	ProgramID int32          `json:"program_id"`
	RuleType  string         `json:"rule_type"`
	RuleValue sql.NullString `json:"rule_value"`
}

type ProgramRequiredField struct {
	ProgramID int32                          `json:"program_id"`
	FieldName ProgramRequiredFieldsFieldName `json:"field_name"`
}

type Student struct {
	StudentID int32     `json:"student_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Dob       time.Time `json:"dob"`
}

type StudentAcademic struct {
	StudentID int32  `json:"student_id"`
	ExamLevel string `json:"exam_level"`
	Year      int32  `json:"year"`
	RollNo    string `json:"roll_no"`
	RegNo     string `json:"reg_no"`
	Gpa       string `json:"gpa"`
	Board     string `json:"board"`
	EduGroup  string `json:"edu_group"`
}

type StudentMobile struct {
	StudentID int32                  `json:"student_id"`
	MobileNo  string                 `json:"mobile_no"`
	OwnerType StudentMobileOwnerType `json:"owner_type"`
}

type StudentProfileInfo struct {
	StudentID  int32                       `json:"student_id"`
	FieldName  StudentProfileInfoFieldName `json:"field_name"`
	FieldValue string                      `json:"field_value"`
}

type StudentSubjectMark struct {
	StudentID   int32          `json:"student_id"`
	ExamLevel   string         `json:"exam_level"`
	SubjectName string         `json:"subject_name"`
	Marks       string         `json:"marks"`
	Grade       sql.NullString `json:"grade"`
}

type University struct {
	UID                   int32          `json:"u_id"`
	Website               string         `json:"website"`
	Location              sql.NullString `json:"location"`
	LogoUrl               sql.NullString `json:"logo_url"`
	UniversityDescription sql.NullString `json:"university_description"`
	UniversityHistory     sql.NullString `json:"university_history"`
	UName                 string         `json:"u_name"`
}

type UniversityAlbum struct {
	AlbumID      int32  `json:"album_id"`
	UID          int32  `json:"u_id"`
	PictureTitle string `json:"picture_title"`
	PictureUrl   string `json:"picture_url"`
}

type UniversityDepartment struct {
	DeptID          int32          `json:"dept_id"`
	UID             int32          `json:"u_id"`
	DeptName        string         `json:"dept_name"`
	DeptDescription sql.NullString `json:"dept_description"`
	TotalSeats      int32          `json:"total_seats"`
}

type UniversityTransport struct {
	UID            int32  `json:"u_id"`
	TransportRoute string `json:"transport_route"`
	EstTravelTime  string `json:"est_travel_time"`
}
