// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type AdmissionTest struct {
	TestID       int32          `json:"test_id"`
	ExamUnit     sql.NullString `json:"exam_unit"`
	ExamCenter   sql.NullString `json:"exam_center"`
	PrereqTestID sql.NullInt32  `json:"prereq_test_id"`
}

type Application struct {
	AppID     int32        `json:"app_id"`
	SubDate   sql.NullTime `json:"sub_date"`
	Status    string       `json:"status"`
	ProgramID int32        `json:"program_id"`
	StudentID int32        `json:"student_id"`
}

type Conduct struct {
	UID    int32 `json:"u_id"`
	TestID int32 `json:"test_id"`
}

type Gife struct {
	StudentID     int32          `json:"student_id"`
	TestID        int32          `json:"test_id"`
	Marks         sql.NullString `json:"marks"`
	MeritPosition sql.NullInt32  `json:"merit_position"`
}

type Notification struct {
	NotifID   int32        `json:"notif_id"`
	StudentID int32        `json:"student_id"`
	Message   string       `json:"message"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Payment struct {
	PaymentID int32        `json:"payment_id"`
	TxID      string       `json:"tx_id"`
	Amount    string       `json:"amount"`
	Status    string       `json:"status"`
	Method    string       `json:"method"`
	Timestamp sql.NullTime `json:"timestamp"`
	AppID     int32        `json:"app_id"`
}

type Program struct {
	ProgramID    int32          `json:"program_id"`
	PName        string         `json:"p_name"`
	PUnit        sql.NullString `json:"p_unit"`
	TotalSeats   int32          `json:"total_seats"`
	PrevCutmarks sql.NullString `json:"prev_cutmarks"`
	Deadline     time.Time      `json:"deadline"`
	UID          int32          `json:"u_id"`
}

type ProgramEligibilityRule struct {
	ProgramID int32          `json:"program_id"`
	RuleType  string         `json:"rule_type"`
	RuleValue sql.NullString `json:"rule_value"`
}

type Student struct {
	StudentID int32     `json:"student_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Dob       time.Time `json:"dob"`
}

type StudentAcademic struct {
	StudentID int32  `json:"student_id"`
	ExamLevel string `json:"exam_level"`
	Year      int32  `json:"year"`
	RollNo    string `json:"roll_no"`
	RegNo     string `json:"reg_no"`
	Gpa       string `json:"gpa"`
	Board     string `json:"board"`
}

type StudentMobile struct {
	StudentID int32  `json:"student_id"`
	MobileNo  string `json:"mobile_no"`
}

type University struct {
	UID      int32          `json:"u_id"`
	UName    string         `json:"u_name"`
	Website  string         `json:"website"`
	Location sql.NullString `json:"location"`
}

type UniversityTransport struct {
	UID            int32  `json:"u_id"`
	TransportRoute string `json:"transport_route"`
	EstTravelTime  string `json:"est_travel_time"`
}
