// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :execresult
INSERT INTO Payment (app_id, amount, method, tx_id, status)
VALUES (?, ?, ?, ?, 'SUCCESS')
`

type CreatePaymentParams struct {
	AppID  int32  `json:"app_id"`
	Amount string `json:"amount"`
	Method string `json:"method"`
	TxID   string `json:"tx_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPayment,
		arg.AppID,
		arg.Amount,
		arg.Method,
		arg.TxID,
	)
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT app_id, student_id, program_id, status
FROM Application
WHERE app_id = ? AND student_id = ?
`

type GetApplicationByIDParams struct {
	AppID     int32 `json:"app_id"`
	StudentID int32 `json:"student_id"`
}

type GetApplicationByIDRow struct {
	AppID     int32  `json:"app_id"`
	StudentID int32  `json:"student_id"`
	ProgramID int32  `json:"program_id"`
	Status    string `json:"status"`
}

func (q *Queries) GetApplicationByID(ctx context.Context, arg GetApplicationByIDParams) (GetApplicationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getApplicationByID, arg.AppID, arg.StudentID)
	var i GetApplicationByIDRow
	err := row.Scan(
		&i.AppID,
		&i.StudentID,
		&i.ProgramID,
		&i.Status,
	)
	return i, err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :exec
UPDATE Application
SET status = ?
WHERE app_id = ? AND student_id = ?
`

type UpdateApplicationStatusParams struct {
	Status    string `json:"status"`
	AppID     int32  `json:"app_id"`
	StudentID int32  `json:"student_id"`
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateApplicationStatus, arg.Status, arg.AppID, arg.StudentID)
	return err
}
