// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: programs.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteProgram = `-- name: DeleteProgram :exec
DELETE FROM Program
WHERE program_id = ?
`

func (q *Queries) DeleteProgram(ctx context.Context, programID int32) error {
	_, err := q.db.ExecContext(ctx, deleteProgram, programID)
	return err
}

const getAllProgramsWithRules = `-- name: GetAllProgramsWithRules :many
SELECT
    p.program_id,
    p.p_name,
    u.u_name AS university_name,
    r.rule_type,
    r.rule_value
FROM Program p
JOIN University u ON p.u_id = u.u_id
LEFT JOIN Program_Eligibility_Rules r ON p.program_id = r.program_id
`

type GetAllProgramsWithRulesRow struct {
	ProgramID      int32          `json:"program_id"`
	PName          string         `json:"p_name"`
	UniversityName string         `json:"university_name"`
	RuleType       sql.NullString `json:"rule_type"`
	RuleValue      sql.NullString `json:"rule_value"`
}

func (q *Queries) GetAllProgramsWithRules(ctx context.Context) ([]GetAllProgramsWithRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProgramsWithRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProgramsWithRulesRow
	for rows.Next() {
		var i GetAllProgramsWithRulesRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.PName,
			&i.UniversityName,
			&i.RuleType,
			&i.RuleValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgramByID = `-- name: GetProgramByID :one
SELECT
    p.program_id,
    p.p_name,
    p.p_unit,
    p.total_seats,
    p.prev_cutmarks,
    p.deadline,
    u.u_id,
    u.u_name AS university_name,
    u.website,
    u.location
FROM Program p
JOIN University u ON p.u_id = u.u_id
WHERE p.program_id = ? LIMIT 1
`

type GetProgramByIDRow struct {
	ProgramID      int32          `json:"program_id"`
	PName          string         `json:"p_name"`
	PUnit          sql.NullString `json:"p_unit"`
	TotalSeats     int32          `json:"total_seats"`
	PrevCutmarks   sql.NullString `json:"prev_cutmarks"`
	Deadline       time.Time      `json:"deadline"`
	UID            int32          `json:"u_id"`
	UniversityName string         `json:"university_name"`
	Website        string         `json:"website"`
	Location       sql.NullString `json:"location"`
}

func (q *Queries) GetProgramByID(ctx context.Context, programID int32) (GetProgramByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProgramByID, programID)
	var i GetProgramByIDRow
	err := row.Scan(
		&i.ProgramID,
		&i.PName,
		&i.PUnit,
		&i.TotalSeats,
		&i.PrevCutmarks,
		&i.Deadline,
		&i.UID,
		&i.UniversityName,
		&i.Website,
		&i.Location,
	)
	return i, err
}

const getProgramDetails = `-- name: GetProgramDetails :one
SELECT p.program_id, p.p_name, p.p_unit, p.total_seats, p.prev_cutmarks, p.deadline, p.u_id, u.u_name, u.location
FROM Program p
JOIN University u ON p.u_id = u.u_id
WHERE p.program_id = ? LIMIT 1
`

type GetProgramDetailsRow struct {
	ProgramID    int32          `json:"program_id"`
	PName        string         `json:"p_name"`
	PUnit        sql.NullString `json:"p_unit"`
	TotalSeats   int32          `json:"total_seats"`
	PrevCutmarks sql.NullString `json:"prev_cutmarks"`
	Deadline     time.Time      `json:"deadline"`
	UID          int32          `json:"u_id"`
	UName        string         `json:"u_name"`
	Location     sql.NullString `json:"location"`
}

func (q *Queries) GetProgramDetails(ctx context.Context, programID int32) (GetProgramDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getProgramDetails, programID)
	var i GetProgramDetailsRow
	err := row.Scan(
		&i.ProgramID,
		&i.PName,
		&i.PUnit,
		&i.TotalSeats,
		&i.PrevCutmarks,
		&i.Deadline,
		&i.UID,
		&i.UName,
		&i.Location,
	)
	return i, err
}

const getProgramEligibilityRules = `-- name: GetProgramEligibilityRules :many
SELECT program_id, rule_type, rule_value FROM Program_Eligibility_Rules
WHERE program_id = ?
`

func (q *Queries) GetProgramEligibilityRules(ctx context.Context, programID int32) ([]ProgramEligibilityRule, error) {
	rows, err := q.db.QueryContext(ctx, getProgramEligibilityRules, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgramEligibilityRule
	for rows.Next() {
		var i ProgramEligibilityRule
		if err := rows.Scan(&i.ProgramID, &i.RuleType, &i.RuleValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentProgramRequirements = `-- name: GetStudentProgramRequirements :many
SELECT
    prf.field_name,
    spi.field_value
FROM Program_Required_Fields prf
LEFT JOIN Student_Profile_Info spi
    ON prf.field_name = spi.field_name
    AND spi.student_id = ?
WHERE prf.program_id = ?
`

type GetStudentProgramRequirementsParams struct {
	StudentID int32 `json:"student_id"`
	ProgramID int32 `json:"program_id"`
}

type GetStudentProgramRequirementsRow struct {
	FieldName  ProgramRequiredFieldsFieldName `json:"field_name"`
	FieldValue sql.NullString                 `json:"field_value"`
}

func (q *Queries) GetStudentProgramRequirements(ctx context.Context, arg GetStudentProgramRequirementsParams) ([]GetStudentProgramRequirementsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStudentProgramRequirements, arg.StudentID, arg.ProgramID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentProgramRequirementsRow
	for rows.Next() {
		var i GetStudentProgramRequirementsRow
		if err := rows.Scan(&i.FieldName, &i.FieldValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProgram = `-- name: InsertProgram :execresult
INSERT INTO Program (p_name, p_unit, total_seats, prev_cutmarks, deadline, u_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertProgramParams struct {
	PName        string         `json:"p_name"`
	PUnit        sql.NullString `json:"p_unit"`
	TotalSeats   int32          `json:"total_seats"`
	PrevCutmarks sql.NullString `json:"prev_cutmarks"`
	Deadline     time.Time      `json:"deadline"`
	UID          int32          `json:"u_id"`
}

func (q *Queries) InsertProgram(ctx context.Context, arg InsertProgramParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertProgram,
		arg.PName,
		arg.PUnit,
		arg.TotalSeats,
		arg.PrevCutmarks,
		arg.Deadline,
		arg.UID,
	)
}

const listPrograms = `-- name: ListPrograms :many
SELECT
    p.program_id,
    p.p_name,
    p.p_unit,
    p.total_seats,
    p.prev_cutmarks,
    p.deadline,
    u.u_id,
    u.u_name AS university_name,
    u.location AS university_location
FROM Program p
JOIN University u ON p.u_id = u.u_id
WHERE
    (p.p_name LIKE CONCAT('%', ?, '%') OR u.u_name LIKE CONCAT('%', ?, '%'))
    AND (p.p_unit = ? OR ? = '')
ORDER BY p.program_id DESC
`

type ListProgramsParams struct {
	CONCAT   interface{}    `json:"CONCAT"`
	CONCAT_2 interface{}    `json:"CONCAT_2"`
	PUnit    sql.NullString `json:"p_unit"`
	Column4  interface{}    `json:"column_4"`
}

type ListProgramsRow struct {
	ProgramID          int32          `json:"program_id"`
	PName              string         `json:"p_name"`
	PUnit              sql.NullString `json:"p_unit"`
	TotalSeats         int32          `json:"total_seats"`
	PrevCutmarks       sql.NullString `json:"prev_cutmarks"`
	Deadline           time.Time      `json:"deadline"`
	UID                int32          `json:"u_id"`
	UniversityName     string         `json:"university_name"`
	UniversityLocation sql.NullString `json:"university_location"`
}

func (q *Queries) ListPrograms(ctx context.Context, arg ListProgramsParams) ([]ListProgramsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPrograms,
		arg.CONCAT,
		arg.CONCAT_2,
		arg.PUnit,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProgramsRow
	for rows.Next() {
		var i ListProgramsRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.PName,
			&i.PUnit,
			&i.TotalSeats,
			&i.PrevCutmarks,
			&i.Deadline,
			&i.UID,
			&i.UniversityName,
			&i.UniversityLocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsByUniversity = `-- name: ListProgramsByUniversity :many
SELECT program_id, p_name, p_unit, total_seats, prev_cutmarks, deadline, u_id FROM Program
WHERE u_id = ?
`

func (q *Queries) ListProgramsByUniversity(ctx context.Context, uID int32) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsByUniversity, uID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Program
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ProgramID,
			&i.PName,
			&i.PUnit,
			&i.TotalSeats,
			&i.PrevCutmarks,
			&i.Deadline,
			&i.UID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniversities = `-- name: ListUniversities :many
SELECT u_id, u_name, website, location, logo_url, university_description, university_history FROM University
`

func (q *Queries) ListUniversities(ctx context.Context) ([]University, error) {
	rows, err := q.db.QueryContext(ctx, listUniversities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []University
	for rows.Next() {
		var i University
		if err := rows.Scan(
			&i.UID,
			&i.UName,
			&i.Website,
			&i.Location,
			&i.LogoUrl,
			&i.UniversityDescription,
			&i.UniversityHistory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgram = `-- name: UpdateProgram :exec
UPDATE Program
SET p_name = ?, p_unit = ?, total_seats = ?, prev_cutmarks = ?, deadline = ?, u_id = ?
WHERE program_id = ?
`

type UpdateProgramParams struct {
	PName        string         `json:"p_name"`
	PUnit        sql.NullString `json:"p_unit"`
	TotalSeats   int32          `json:"total_seats"`
	PrevCutmarks sql.NullString `json:"prev_cutmarks"`
	Deadline     time.Time      `json:"deadline"`
	UID          int32          `json:"u_id"`
	ProgramID    int32          `json:"program_id"`
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) error {
	_, err := q.db.ExecContext(ctx, updateProgram,
		arg.PName,
		arg.PUnit,
		arg.TotalSeats,
		arg.PrevCutmarks,
		arg.Deadline,
		arg.UID,
		arg.ProgramID,
	)
	return err
}
