// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: programs.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getProgramDetails = `-- name: GetProgramDetails :one
SELECT p.program_id, p.p_name, p.p_unit, p.total_seats, p.prev_cutmarks, p.deadline, p.u_id, u.u_name, u.location
FROM Program p
JOIN University u ON p.u_id = u.u_id
WHERE p.program_id = ? LIMIT 1
`

type GetProgramDetailsRow struct {
	ProgramID    int32          `json:"program_id"`
	PName        string         `json:"p_name"`
	PUnit        sql.NullString `json:"p_unit"`
	TotalSeats   int32          `json:"total_seats"`
	PrevCutmarks sql.NullString `json:"prev_cutmarks"`
	Deadline     time.Time      `json:"deadline"`
	UID          int32          `json:"u_id"`
	UName        string         `json:"u_name"`
	Location     sql.NullString `json:"location"`
}

func (q *Queries) GetProgramDetails(ctx context.Context, programID int32) (GetProgramDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getProgramDetails, programID)
	var i GetProgramDetailsRow
	err := row.Scan(
		&i.ProgramID,
		&i.PName,
		&i.PUnit,
		&i.TotalSeats,
		&i.PrevCutmarks,
		&i.Deadline,
		&i.UID,
		&i.UName,
		&i.Location,
	)
	return i, err
}

const getProgramEligibilityRules = `-- name: GetProgramEligibilityRules :many
SELECT program_id, rule_type, rule_value FROM Program_Eligibility_Rules
WHERE program_id = ?
`

func (q *Queries) GetProgramEligibilityRules(ctx context.Context, programID int32) ([]ProgramEligibilityRule, error) {
	rows, err := q.db.QueryContext(ctx, getProgramEligibilityRules, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgramEligibilityRule
	for rows.Next() {
		var i ProgramEligibilityRule
		if err := rows.Scan(&i.ProgramID, &i.RuleType, &i.RuleValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsByUniversity = `-- name: ListProgramsByUniversity :many
SELECT program_id, p_name, p_unit, total_seats, prev_cutmarks, deadline, u_id FROM Program
WHERE u_id = ?
`

func (q *Queries) ListProgramsByUniversity(ctx context.Context, uID int32) ([]Program, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsByUniversity, uID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Program
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ProgramID,
			&i.PName,
			&i.PUnit,
			&i.TotalSeats,
			&i.PrevCutmarks,
			&i.Deadline,
			&i.UID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniversities = `-- name: ListUniversities :many
SELECT u_id, u_name, website, location FROM University
`

func (q *Queries) ListUniversities(ctx context.Context) ([]University, error) {
	rows, err := q.db.QueryContext(ctx, listUniversities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []University
	for rows.Next() {
		var i University
		if err := rows.Scan(
			&i.UID,
			&i.UName,
			&i.Website,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
