// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddStudentAcademic(ctx context.Context, arg AddStudentAcademicParams) error
	AdminUpdateApplicationStatus(ctx context.Context, arg AdminUpdateApplicationStatusParams) error
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (sql.Result, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (sql.Result, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (sql.Result, error)
	DeleteUniversity(ctx context.Context, uID int32) error
	GetAllProgramsWithRules(ctx context.Context) ([]GetAllProgramsWithRulesRow, error)
	GetApplicationByID(ctx context.Context, arg GetApplicationByIDParams) (GetApplicationByIDRow, error)
	GetProgramByID(ctx context.Context, programID int32) (GetProgramByIDRow, error)
	GetProgramDetails(ctx context.Context, programID int32) (GetProgramDetailsRow, error)
	GetProgramEligibilityRules(ctx context.Context, programID int32) ([]ProgramEligibilityRule, error)
	GetProgramRequiredFields(ctx context.Context, programID int32) ([]ProgramRequiredFieldsFieldName, error)
	GetStudentAcademics(ctx context.Context, studentID int32) ([]StudentAcademic, error)
	GetStudentApplications(ctx context.Context, studentID int32) ([]GetStudentApplicationsRow, error)
	GetStudentByEmail(ctx context.Context, email string) (Student, error)
	GetStudentByID(ctx context.Context, studentID int32) (Student, error)
	GetStudentProfileFields(ctx context.Context, studentID int32) ([]StudentProfileInfoFieldName, error)
	GetStudentProgramRequirements(ctx context.Context, arg GetStudentProgramRequirementsParams) ([]GetStudentProgramRequirementsRow, error)
	GetStudentSubjectMarks(ctx context.Context, arg GetStudentSubjectMarksParams) ([]GetStudentSubjectMarksRow, error)
	GetStudentTestResults(ctx context.Context, studentID int32) ([]GetStudentTestResultsRow, error)
	GetUniversityApplications(ctx context.Context, uID int32) ([]GetUniversityApplicationsRow, error)
	GetUniversityByID(ctx context.Context, uID int32) (University, error)
	InsertUniversity(ctx context.Context, arg InsertUniversityParams) (sql.Result, error)
	ListPrograms(ctx context.Context, arg ListProgramsParams) ([]ListProgramsRow, error)
	ListProgramsByUniversity(ctx context.Context, uID int32) ([]Program, error)
	ListUniversities(ctx context.Context) ([]University, error)
	RecordPayment(ctx context.Context, arg RecordPaymentParams) (sql.Result, error)
	RecordTestResult(ctx context.Context, arg RecordTestResultParams) error
	UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) error
	UpdateUniversity(ctx context.Context, arg UpdateUniversityParams) error
	UpsertStudentProfileField(ctx context.Context, arg UpsertStudentProfileFieldParams) error
}

var _ Querier = (*Queries)(nil)
