// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddStudentAcademic(ctx context.Context, arg AddStudentAcademicParams) error
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (sql.Result, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (sql.Result, error)
	GetAllProgramsWithRules(ctx context.Context) ([]GetAllProgramsWithRulesRow, error)
	GetProgramByID(ctx context.Context, programID int32) (GetProgramByIDRow, error)
	GetProgramDetails(ctx context.Context, programID int32) (GetProgramDetailsRow, error)
	GetProgramEligibilityRules(ctx context.Context, programID int32) ([]ProgramEligibilityRule, error)
	GetStudentAcademics(ctx context.Context, studentID int32) ([]StudentAcademic, error)
	GetStudentApplications(ctx context.Context, studentID int32) ([]GetStudentApplicationsRow, error)
	GetStudentByEmail(ctx context.Context, email string) (Student, error)
	GetStudentByID(ctx context.Context, studentID int32) (Student, error)
	GetStudentTestResults(ctx context.Context, studentID int32) ([]GetStudentTestResultsRow, error)
	ListPrograms(ctx context.Context, arg ListProgramsParams) ([]ListProgramsRow, error)
	ListProgramsByUniversity(ctx context.Context, uID int32) ([]Program, error)
	ListUniversities(ctx context.Context) ([]University, error)
	RecordPayment(ctx context.Context, arg RecordPaymentParams) (sql.Result, error)
	RecordTestResult(ctx context.Context, arg RecordTestResultParams) error
	UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) error
}

var _ Querier = (*Queries)(nil)
