// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addStudentAcademic = `-- name: AddStudentAcademic :exec
INSERT INTO Student_Academics (student_id, exam_level, year, roll_no, reg_no, gpa, board, edu_group)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE year = VALUES(year), roll_no = VALUES(roll_no), reg_no = VALUES(reg_no), gpa = VALUES(gpa), board = VALUES(board), edu_group = VALUES(edu_group)
`

type AddStudentAcademicParams struct {
	StudentID int32  `json:"student_id"`
	ExamLevel string `json:"exam_level"`
	Year      int32  `json:"year"`
	RollNo    string `json:"roll_no"`
	RegNo     string `json:"reg_no"`
	Gpa       string `json:"gpa"`
	Board     string `json:"board"`
	EduGroup  string `json:"edu_group"`
}

func (q *Queries) AddStudentAcademic(ctx context.Context, arg AddStudentAcademicParams) error {
	_, err := q.db.ExecContext(ctx, addStudentAcademic,
		arg.StudentID,
		arg.ExamLevel,
		arg.Year,
		arg.RollNo,
		arg.RegNo,
		arg.Gpa,
		arg.Board,
		arg.EduGroup,
	)
	return err
}

const createNotification = `-- name: CreateNotification :execresult
INSERT INTO Notification (student_id, message)
VALUES (?, ?)
`

type CreateNotificationParams struct {
	StudentID int32  `json:"student_id"`
	Message   string `json:"message"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNotification, arg.StudentID, arg.Message)
}

const createStudent = `-- name: CreateStudent :execresult
INSERT INTO Student (first_name, last_name, email, password, dob)
VALUES (?, ?, ?, ?, ?)
`

type CreateStudentParams struct {
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Dob       time.Time `json:"dob"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createStudent,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.Dob,
	)
}

const deleteStudentMobile = `-- name: DeleteStudentMobile :execresult
DELETE FROM Student_Mobile
WHERE student_id = ? AND mobile_no = ?
`

type DeleteStudentMobileParams struct {
	StudentID int32  `json:"student_id"`
	MobileNo  string `json:"mobile_no"`
}

func (q *Queries) DeleteStudentMobile(ctx context.Context, arg DeleteStudentMobileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteStudentMobile, arg.StudentID, arg.MobileNo)
}

const getStudentAcademics = `-- name: GetStudentAcademics :many
SELECT student_id, exam_level, year, roll_no, reg_no, gpa, board, edu_group FROM Student_Academics
WHERE student_id = ?
`

func (q *Queries) GetStudentAcademics(ctx context.Context, studentID int32) ([]StudentAcademic, error) {
	rows, err := q.db.QueryContext(ctx, getStudentAcademics, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentAcademic
	for rows.Next() {
		var i StudentAcademic
		if err := rows.Scan(
			&i.StudentID,
			&i.ExamLevel,
			&i.Year,
			&i.RollNo,
			&i.RegNo,
			&i.Gpa,
			&i.Board,
			&i.EduGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentByEmail = `-- name: GetStudentByEmail :one
SELECT student_id, first_name, last_name, email, password, dob FROM Student
WHERE email = ? LIMIT 1
`

func (q *Queries) GetStudentByEmail(ctx context.Context, email string) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByEmail, email)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Dob,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT student_id, first_name, last_name, email, password, dob FROM Student
WHERE student_id = ? LIMIT 1
`

func (q *Queries) GetStudentByID(ctx context.Context, studentID int32) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByID, studentID)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Dob,
	)
	return i, err
}

const getStudentMobiles = `-- name: GetStudentMobiles :many
SELECT student_id, mobile_no, owner_type
FROM Student_Mobile
WHERE student_id = ?
`

func (q *Queries) GetStudentMobiles(ctx context.Context, studentID int32) ([]StudentMobile, error) {
	rows, err := q.db.QueryContext(ctx, getStudentMobiles, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentMobile
	for rows.Next() {
		var i StudentMobile
		if err := rows.Scan(&i.StudentID, &i.MobileNo, &i.OwnerType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentNotifications = `-- name: GetStudentNotifications :many
SELECT notif_id, student_id, message, created_at
FROM Notification
WHERE student_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetStudentNotifications(ctx context.Context, studentID int32) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getStudentNotifications, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotifID,
			&i.StudentID,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentSubjectMarks = `-- name: GetStudentSubjectMarks :many
SELECT subject_name, marks, grade
FROM Student_Subject_Marks
WHERE student_id = ? AND exam_level = ?
`

type GetStudentSubjectMarksParams struct {
	StudentID int32  `json:"student_id"`
	ExamLevel string `json:"exam_level"`
}

type GetStudentSubjectMarksRow struct {
	SubjectName string         `json:"subject_name"`
	Marks       string         `json:"marks"`
	Grade       sql.NullString `json:"grade"`
}

func (q *Queries) GetStudentSubjectMarks(ctx context.Context, arg GetStudentSubjectMarksParams) ([]GetStudentSubjectMarksRow, error) {
	rows, err := q.db.QueryContext(ctx, getStudentSubjectMarks, arg.StudentID, arg.ExamLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentSubjectMarksRow
	for rows.Next() {
		var i GetStudentSubjectMarksRow
		if err := rows.Scan(&i.SubjectName, &i.Marks, &i.Grade); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertStudentMobile = `-- name: InsertStudentMobile :execresult
INSERT INTO Student_Mobile (student_id, mobile_no, owner_type)
VALUES (?, ?, ?)
`

type InsertStudentMobileParams struct {
	StudentID int32                  `json:"student_id"`
	MobileNo  string                 `json:"mobile_no"`
	OwnerType StudentMobileOwnerType `json:"owner_type"`
}

func (q *Queries) InsertStudentMobile(ctx context.Context, arg InsertStudentMobileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertStudentMobile, arg.StudentID, arg.MobileNo, arg.OwnerType)
}

const updateStudentMobile = `-- name: UpdateStudentMobile :execresult
UPDATE Student_Mobile
SET mobile_no = ?, owner_type = ?
WHERE student_id = ? AND mobile_no = ?
`

type UpdateStudentMobileParams struct {
	MobileNo   string                 `json:"mobile_no"`
	OwnerType  StudentMobileOwnerType `json:"owner_type"`
	StudentID  int32                  `json:"student_id"`
	MobileNo_2 string                 `json:"mobile_no_2"`
}

func (q *Queries) UpdateStudentMobile(ctx context.Context, arg UpdateStudentMobileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateStudentMobile,
		arg.MobileNo,
		arg.OwnerType,
		arg.StudentID,
		arg.MobileNo_2,
	)
}

const upsertStudentProfileField = `-- name: UpsertStudentProfileField :exec
INSERT INTO Student_Profile_Info (student_id, field_name, field_value)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE field_value = VALUES(field_value)
`

type UpsertStudentProfileFieldParams struct {
	StudentID  int32                       `json:"student_id"`
	FieldName  StudentProfileInfoFieldName `json:"field_name"`
	FieldValue string                      `json:"field_value"`
}

func (q *Queries) UpsertStudentProfileField(ctx context.Context, arg UpsertStudentProfileFieldParams) error {
	_, err := q.db.ExecContext(ctx, upsertStudentProfileField, arg.StudentID, arg.FieldName, arg.FieldValue)
	return err
}

const upsertStudentSubjectMark = `-- name: UpsertStudentSubjectMark :exec
INSERT INTO Student_Subject_Marks (student_id, exam_level, subject_name, marks, grade)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE marks = VALUES(marks), grade = VALUES(grade)
`

type UpsertStudentSubjectMarkParams struct {
	StudentID   int32          `json:"student_id"`
	ExamLevel   string         `json:"exam_level"`
	SubjectName string         `json:"subject_name"`
	Marks       string         `json:"marks"`
	Grade       sql.NullString `json:"grade"`
}

func (q *Queries) UpsertStudentSubjectMark(ctx context.Context, arg UpsertStudentSubjectMarkParams) error {
	_, err := q.db.ExecContext(ctx, upsertStudentSubjectMark,
		arg.StudentID,
		arg.ExamLevel,
		arg.SubjectName,
		arg.Marks,
		arg.Grade,
	)
	return err
}
