// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addStudentAcademic = `-- name: AddStudentAcademic :exec
INSERT INTO Student_Academics (student_id, exam_level, year, roll_no, reg_no, gpa, board)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AddStudentAcademicParams struct {
	StudentID int32  `json:"student_id"`
	ExamLevel string `json:"exam_level"`
	Year      int32  `json:"year"`
	RollNo    string `json:"roll_no"`
	RegNo     string `json:"reg_no"`
	Gpa       string `json:"gpa"`
	Board     string `json:"board"`
}

func (q *Queries) AddStudentAcademic(ctx context.Context, arg AddStudentAcademicParams) error {
	_, err := q.db.ExecContext(ctx, addStudentAcademic,
		arg.StudentID,
		arg.ExamLevel,
		arg.Year,
		arg.RollNo,
		arg.RegNo,
		arg.Gpa,
		arg.Board,
	)
	return err
}

const createStudent = `-- name: CreateStudent :execresult
INSERT INTO Student (first_name, last_name, email, password, dob)
VALUES (?, ?, ?, ?, ?)
`

type CreateStudentParams struct {
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Dob       time.Time `json:"dob"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createStudent,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.Dob,
	)
}

const getStudentAcademics = `-- name: GetStudentAcademics :many
SELECT student_id, exam_level, year, roll_no, reg_no, gpa, board, edu_group FROM Student_Academics
WHERE student_id = ?
`

func (q *Queries) GetStudentAcademics(ctx context.Context, studentID int32) ([]StudentAcademic, error) {
	rows, err := q.db.QueryContext(ctx, getStudentAcademics, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentAcademic
	for rows.Next() {
		var i StudentAcademic
		if err := rows.Scan(
			&i.StudentID,
			&i.ExamLevel,
			&i.Year,
			&i.RollNo,
			&i.RegNo,
			&i.Gpa,
			&i.Board,
			&i.EduGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentByEmail = `-- name: GetStudentByEmail :one
SELECT student_id, first_name, last_name, email, password, dob FROM Student
WHERE email = ? LIMIT 1
`

func (q *Queries) GetStudentByEmail(ctx context.Context, email string) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByEmail, email)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Dob,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT student_id, first_name, last_name, email, password, dob FROM Student
WHERE student_id = ? LIMIT 1
`

func (q *Queries) GetStudentByID(ctx context.Context, studentID int32) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByID, studentID)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Dob,
	)
	return i, err
}

const getStudentSubjectMarks = `-- name: GetStudentSubjectMarks :many
SELECT subject_name, marks, grade
FROM Student_Subject_Marks
WHERE student_id = ? AND exam_level = ?
`

type GetStudentSubjectMarksParams struct {
	StudentID int32  `json:"student_id"`
	ExamLevel string `json:"exam_level"`
}

type GetStudentSubjectMarksRow struct {
	SubjectName string         `json:"subject_name"`
	Marks       string         `json:"marks"`
	Grade       sql.NullString `json:"grade"`
}

func (q *Queries) GetStudentSubjectMarks(ctx context.Context, arg GetStudentSubjectMarksParams) ([]GetStudentSubjectMarksRow, error) {
	rows, err := q.db.QueryContext(ctx, getStudentSubjectMarks, arg.StudentID, arg.ExamLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentSubjectMarksRow
	for rows.Next() {
		var i GetStudentSubjectMarksRow
		if err := rows.Scan(&i.SubjectName, &i.Marks, &i.Grade); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStudentProfileField = `-- name: UpsertStudentProfileField :exec
INSERT INTO Student_Profile_Info (student_id, field_name, field_value)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE field_value = VALUES(field_value)
`

type UpsertStudentProfileFieldParams struct {
	StudentID  int32                       `json:"student_id"`
	FieldName  StudentProfileInfoFieldName `json:"field_name"`
	FieldValue string                      `json:"field_value"`
}

func (q *Queries) UpsertStudentProfileField(ctx context.Context, arg UpsertStudentProfileFieldParams) error {
	_, err := q.db.ExecContext(ctx, upsertStudentProfileField, arg.StudentID, arg.FieldName, arg.FieldValue)
	return err
}
