// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tests.sql

package db

import (
	"context"
	"database/sql"
)

const getStudentTestResults = `-- name: GetStudentTestResults :many
SELECT g.marks, g.merit_position, t.exam_unit, u.u_name
FROM Gives g
JOIN Admission_Test t ON g.test_id = t.test_id
JOIN Conducts c ON t.test_id = c.test_id
JOIN University u ON c.u_id = u.u_id
WHERE g.student_id = ?
`

type GetStudentTestResultsRow struct {
	Marks         sql.NullString `json:"marks"`
	MeritPosition sql.NullInt32  `json:"merit_position"`
	ExamUnit      sql.NullString `json:"exam_unit"`
	UName         string         `json:"u_name"`
}

func (q *Queries) GetStudentTestResults(ctx context.Context, studentID int32) ([]GetStudentTestResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStudentTestResults, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentTestResultsRow
	for rows.Next() {
		var i GetStudentTestResultsRow
		if err := rows.Scan(
			&i.Marks,
			&i.MeritPosition,
			&i.ExamUnit,
			&i.UName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTestResult = `-- name: RecordTestResult :exec
INSERT INTO Gives (student_id, test_id, marks, merit_position)
VALUES (?, ?, ?, ?)
`

type RecordTestResultParams struct {
	StudentID     int32          `json:"student_id"`
	TestID        int32          `json:"test_id"`
	Marks         sql.NullString `json:"marks"`
	MeritPosition sql.NullInt32  `json:"merit_position"`
}

func (q *Queries) RecordTestResult(ctx context.Context, arg RecordTestResultParams) error {
	_, err := q.db.ExecContext(ctx, recordTestResult,
		arg.StudentID,
		arg.TestID,
		arg.Marks,
		arg.MeritPosition,
	)
	return err
}
