// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: university.sql

package db

import (
	"context"
	"database/sql"
)

const deleteUniversity = `-- name: DeleteUniversity :exec
DELETE FROM University
WHERE u_id = ?
`

func (q *Queries) DeleteUniversity(ctx context.Context, uID int32) error {
	_, err := q.db.ExecContext(ctx, deleteUniversity, uID)
	return err
}

const getUniversityByID = `-- name: GetUniversityByID :one
SELECT u_id, u_name, website, location, logo_url
FROM University
WHERE u_id = ?
`

func (q *Queries) GetUniversityByID(ctx context.Context, uID int32) (University, error) {
	row := q.db.QueryRowContext(ctx, getUniversityByID, uID)
	var i University
	err := row.Scan(
		&i.UID,
		&i.UName,
		&i.Website,
		&i.Location,
		&i.LogoUrl,
	)
	return i, err
}

const insertUniversity = `-- name: InsertUniversity :execresult
INSERT INTO University (u_name, website, location, logo_url)
VALUES (?, ?, ?, ?)
`

type InsertUniversityParams struct {
	UName    string         `json:"u_name"`
	Website  string         `json:"website"`
	Location sql.NullString `json:"location"`
	LogoUrl  sql.NullString `json:"logo_url"`
}

func (q *Queries) InsertUniversity(ctx context.Context, arg InsertUniversityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertUniversity,
		arg.UName,
		arg.Website,
		arg.Location,
		arg.LogoUrl,
	)
}

const updateUniversity = `-- name: UpdateUniversity :exec
UPDATE University
SET u_name = ?, website = ?, location = ?, logo_url = ?
WHERE u_id = ?
`

type UpdateUniversityParams struct {
	UName    string         `json:"u_name"`
	Website  string         `json:"website"`
	Location sql.NullString `json:"location"`
	LogoUrl  sql.NullString `json:"logo_url"`
	UID      int32          `json:"u_id"`
}

func (q *Queries) UpdateUniversity(ctx context.Context, arg UpdateUniversityParams) error {
	_, err := q.db.ExecContext(ctx, updateUniversity,
		arg.UName,
		arg.Website,
		arg.Location,
		arg.LogoUrl,
		arg.UID,
	)
	return err
}
